### ISSUE TITLE
Document File Hashes

### ISSUE THREAD

**Issue by jjfallete** [ITAYC0HEN/SUNBURST-Cracked#1]
Good work.

Can you document the SHA256/SHA1/MD5 hashes of which SolarWinds.Orion.Core.BusinessLayer.dll file was decompiled here?

**Comment by ITAYC0HEN** [comment]
Thanks for the idea! Added the sha256 in a01f358965525bee34ad026acd9dfda3d488fdd8
From what I inspected, the malicious class that was added to the trojaned SolarWinds was the same across all the trojaned binaries. Do you know otherwise?

**Comment by jjfallete** [comment]
Thanks. I am not aware of variants to the code across DLLs, but thought it was worth noting to aid the community should it surface that there is.
